### PR TITLE
Rename script, change "." to "_", fix data files

### PR DESCRIPTION
**Pull request by ebuhle**
While you were editing the analysis code, I was editing formatting throughout the script to change `.` to `_` in variable names. I also renamed the script and made one or two other small changes.

Other file changes should not conflict with `master`.

### CODE REVIEW

**Comment by erlwagne** [comment]
God I hope this works. Here we go...

**Comment by erlwagne** [comment]
There’s hope for me yet!

**Comment by ebuhle** [comment]
Hmm, maybe I trumpeted too soon. You still need to merge the pull request into `master`, but it looks like you can't do that because there are still unresolved conflicts. Or is it only grayed out for me because I'm not the repo owner? (Confession: this is also my first pull request.)

**Comment by erlwagne** [comment]
I think that did it?

**Comment by ebuhle** [comment]
Yes, except you missed some of the weird formatting inserted by git merge at line 173ff.

**Comment by erlwagne** [comment]
Ack. Does that mean I have to go back?

**Comment by erlwagne** [comment]
Or should I just delete it from my end and then push it back?

**Comment by ebuhle** [comment]
No, it's literally just text that it inserted into the file like fingerprints. You just delete it and carry on.

**Comment by erlwagne** [comment]
Ah, okay, fine.

**Comment by ebuhle** [comment]
I didn't want to do it, because I'm trying to limit my current edits to the data section to make the next pull request conflicts (which are inevitable, since we're both editing the same file) simple to resolve.

**Comment by erlwagne** [comment]
Oh, okay. I'll just delete it, etc.

**Comment by erlwagne** [comment]
Okay, done. Whew. Heady stuff.

**Comment by ebuhle** [comment]
The manual conflict resolution is a PITA, but it only comes up b/c we're both editing the same file, which IME is not a frequent occurrence.

**Comment by erlwagne** [comment]
Yeah, that was a little nerve-wracking, but glad to have made it through unscathed. And the underscores do look very nice.

**Pull request merged**
